project_id                      = "deep-book-ocr"
region                          = "asia-northeast1"
bucket_rotation_key             = "v1"
bucket_location                 = "ASIA-NORTHEAST1"
documentai_location             = "us"
functions_service_account_email = "github-actions-sa-0488@deep-book-ocr.iam.gserviceaccount.com"
